name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Check formatting with black
      run: |
        black --check jaxley tests
    
    - name: Check imports with isort
      run: |
        isort -c jaxley tests

    - name: clone tridiax repo
      uses: actions/checkout@v1  
      with:
        owner: jaxleyverse
        repository: tridiax
        access-token: ${{secrets.ACCESS_TOKEN}}

    - name: install tridiax
      run: |
        cd triadax
        python -m pip install -e .
    
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest -m tests/ --cov=jaxley --cov-report=xml
      
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #     env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
